### ISSUE TITLE
from train.eval import show_results ModuleNotFoundError: No module named 'train.eval'

### ISSUE THREAD

**Issue by RichardWang11** [he159ok/CLUR_UncertaintyEst_FewShot_TextCls#1]
Please help me solve this problem... I run it in Google colab environment, and I clone from this repo... It seems like miss a file in train folder named eval...

**Comment by he159ok** [comment]
Sincerely sorry for the inconvenience.

I have changed ``drop_entropy_eval_contrastive_var.py'' into a version where ``train.eval'' is no longer required.

Please update the train->drop_entropy_eval_contrastive_var.py in your Google colab.

Have a nice day.

**Comment by RichardWang11** [comment]
Thank you for your prompt reply!
